name: Coverage
on: pull_request

jobs:
  coverage:
    runs-on: ubuntu-latest
    environment: devnet
    env:
      ENVIRONMENT: devnet
      DOMAIN: ztx.io
      TOKEN_NAME: "XTZ Token"
      TOKEN_SYMBOL: XTZ
      ARBITRUM_TESTNET_SEPOLIA_RPC_URL: ${{ vars.ARBITRUM_TESTNET_SEPOLIA_RPC_URL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: hrishikesh-kadam/setup-lcov@v1

      - run: |
          forge coverage --report lcov
          lcov --rc lcov_branch_coverage=1 --remove lcov.info -o lcov.info 'test/*' 'script/*'

      - uses: zgosalvez/github-actions-report-lcov@v3
        with:
          coverage-files: lcov.info
          minimum-coverage: 80
          artifact-name: tuxedo-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
