name: Slither
on:
    push:

jobs:
    analyze:
        if: false
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive
            - uses: crytic/slither-action@v0.3.0
