name: Tests
on:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        environment: devnet
        env:
            ENVIRONMENT: devnet
            DOMAIN: example.com
            TOKEN_NAME: "TKN Token"
            TOKEN_SYMBOL: TKN
            ARBITRUM_TESTNET_SEPOLIA_RPC_URL: ${{ vars.ARBITRUM_TESTNET_SEPOLIA_RPC_URL }}
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - run: |
                  npm install

            - uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly-94ae8974c1ac479f8d6c8ba5832b852afccfd0c5

            - name: Run Forge build
              run: |
                  forge --version
                  forge build --sizes
              id: build

            - name: Unit tests
              run: |
                  npm run test:unit

            - name: Integration tests
              run: |
                  npm run test:integration
