name: Tests
on:
    push:

jobs:
    test:
        runs-on: ubuntu-latest
        environment: devnet
        env:
            ENVIRONMENT: devnet
            DOMAIN: ztx.io
            TOKEN_NAME: "XTZ Token"
            TOKEN_SYMBOL: XTZ
            ARBITRUM_TESTNET_SEPOLIA_RPC_URL: ${{ vars.ARBITRUM_TESTNET_SEPOLIA_RPC_URL}}
            ARBITRUM_MAINNET_RPC_URL: ${{ vars.ARBITRUM_MAINNET_RPC_URL }}
        steps:
            - uses: actions/checkout@v3
              with:
                  submodules: recursive

            - uses: actions/setup-node@v3
              with:
                  node-version: 18

            - run: |
                  npm install

            - uses: foundry-rs/foundry-toolchain@v1
              with:
                  version: nightly

            - name: Run Forge build
              run: |
                  forge --version
                  forge build --sizes
              id: build

            - name: Unit tests
              run: |
                  npm run test:unit

            - name: Integration tests
              run: |
                  npm run test:integration:mainnet
